### PR TITLE
Implement --latest

### LINKED ISSUE #11: Option to always build latest version
When building a package, especially a dev package, it can happen that the latest version is not possible to build due to conflicts in its dependency cone. Instead, orb may decide to build an earlier version of the package. This may be desirable in some cases(?), but in other cases such as https://builds.robur.coop/ it is undesirable and surprising behavior. In that case it is desirable to fail with a suitable error message.

One could specify an exact version at the command line of orb to avoid this problem, but in the case of https://builds.robur.coop/ it would be an annoying maintenance burden.

### PR DESCRIPTION
**Pull request by reynir**
The flag --latest makes orb add a constraint on the specified package to only attempt to build the latest package.

The relevant code `OpamPackage.max_version (Lazy.force st.available_packages) name`  was found in the implementation of `OpamSwitchState.get_package`. This takes into consideration the `available:` field. We may want to use `OpamPackage.max_version st.packages name` instead.

I need to figure out how to test this.

Fixes #11.

### CODE REVIEW

**Comment by hannesm** [comment]
from the code, it looks fine to me. in respect to testing, maybe just use robur/unikernel-repo at 31d1d569b15af7a8ebb02d15ebb9cec301465b78 and build builder-web (which then should error out due to 0.2.0~dev having conflicts with respect to dream and mirage-crypto-rng).

**Comment by reynir** [comment]
I tried with `available_packages` and `packages` without success. Then in the third try I remembered to pass `--latest` with the code as in this PR. \o/
```
$ dune exec -- orb build --solver-timeout=600 --switch-name=/tmp/myswitch --date=1589138087 --out=out2 --repos="default:https://opam.ocaml.org,unikernels:https://git.robur.coop/robur/unikernel-repo.git#31d1d569b15af7a8ebb02d15ebb9cec301465b78" --latest builder-web
[ORB] using root "/tmp" and switch "myswitch"
[unikernels] no changes from git+https://git.robur.coop/robur/unikernel-repo.git#31d1d569b15af7a8ebb02d15ebb9cec301465b78
[default] no changes from https://opam.ocaml.org
[ORB] Switch myswitch created!
[ORB] Install start
[ORB] Install builder-web (= 0.2.0~dev)
tput: No value for $TERM and no -T specified
[ERROR] Package conflict!
  * No agreement on the version of mirage-crypto-rng:
    - builder-web >= 0.2.0~dev -> dream = 1.0.0~alpha4 -> mirage-crypto-rng < 0.11.0
    - builder-web >= 0.2.0~dev -> mirage-crypto-rng >= 0.11.0
  * Missing dependency:
    - builder-web >= 0.2.0~dev -> dream = 1.0.0~alpha4 -> mirage-crypto-rng < 0.11.0 -> mirage-crypto =
      0.8.1
    unmet availability conditions: 'false'
  * Missing dependency:
    - builder-web >= 0.2.0~dev -> dream = 1.0.0~alpha4 -> mirage-crypto-rng < 0.11.0 -> mirage-crypto =
      0.8.2
    unmet availability conditions: 'false'
  * Missing dependency:
    - builder-web >= 0.2.0~dev -> dream = 1.0.0~alpha4 -> mirage-crypto-rng < 0.11.0 -> mirage-crypto =
      0.8.3
    unmet availability conditions: 'false'
  * Missing dependency:
    - builder-web >= 0.2.0~dev -> dream = 1.0.0~alpha4 -> mirage-crypto-rng < 0.11.0 -> mirage-crypto =
      0.8.4
    unmet availability conditions: 'false'

No solution found, exiting
[ORB] Installation failed with 20
[ORB] cleaning up
[ORB] Switch myswitch removed
```
I'm still unsure whether to use `available_packages` or `packages` -- we probably don't care about packages marked `available: false`, but if it is marked unavailable on our OS we might care - I'm not sure.

Finally, from my first two failed attempts I'm starting to think if this should be the default behavior - that would be a breaking change.

**Comment by reynir** [comment]
The CI errors I don't understand and look unrelated. I'm in favor of merging this as is.

**Comment by hannesm** [comment]
thanks :)

**Pull request merged**
